# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getTautStringApprox <- function(dataVec) {
    .Call('_openCytoFork_getTautStringApprox', PACKAGE = 'openCytoFork', dataVec)
}

collapseData <- function(mat_list, colnames) {
    .Call('_openCytoFork_collapseData', PACKAGE = 'openCytoFork', mat_list, colnames)
}

singleDip <- function(x) {
    .Call('_openCytoFork_singleDip', PACKAGE = 'openCytoFork', x)
}

tsGates <- function(xVec, modePrior) {
    .Call('_openCytoFork_tsGates', PACKAGE = 'openCytoFork', xVec, modePrior)
}

